### ISSUE TITLE
'emacs.C-w' failed.

### ISSUE THREAD

**Issue by ClarkMitchell** [VSCodeEmacs/Emacs#1]
Kill region command is failing for me with
`Running the contributed command: 'emacs.C-w' failed.`
VSCode running from WSL in Windows 10.

**Comment by vdegenne** [comment]
You probably have a conflicting keybinding next to the extension, I just tested in a sandbox and there is no issues.
What version of VSC are you running ?

**Comment by ClarkMitchell** [comment]
Version: 1.41.1 (user setup)
Commit: 26076a4de974ead31f97692a0d32f90d735645c0
Date: 2019-12-18T14:58:56.166Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.18363

**Comment by ClarkMitchell** [comment]
There were some conflicts, but I removed them, restarted and I'm still getting this behavior.

**Comment by vdegenne** [comment]
@ClarkMitchell Are you using the extension in a ssh context ?

**Comment by ClarkMitchell** [comment]
I'm using it with [Remote WSL](https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-wsl).

**Comment by flindeberg** [comment]
I get the same, among others, when using "Remote SSH" (had to use ctrl + c to copy and ctrl + y to yank for an entire stressful day, neither did ctrl + k, ctrl + space, alt + w etc work as intended). 

I'll see if I can dig something concrete up tomorrow, but there seem to be some issues with what should run on the server side and what should run on the client side.

**Comment by flindeberg** [comment]
See https://code.visualstudio.com/api/advanced-topics/remote-extensions#architecture-and-extension-types and https://github.com/hiro-sun/vscode-emacs/issues/60

Possibly that is what is causing it.

**Comment by flindeberg** [comment]
Fixed in PR #3.

**Comment by vdegenne** [comment]
@flindeberg thanks!
