### ISSUE TITLE
List of implemented keybindings / cheatsheet

### ISSUE THREAD

**Issue by ghost** [VSCodeEmacs/Emacs#16]
Hello, can you give the list of implemented key-bindings / cheatsheet? Similar to this one https://www.gnu.org/software/emacs/refcards/pdf/refcard.pdf

**Comment by vdegenne** [comment]
@c01ander Why? This extension aims to emulate Emacs keybindings experience. Which means they are all original Emacs keybindings. And there are tone of Emacs Cheatsheets available on the internet already.
