### ISSUE TITLE
Pasting not replaces selection

### ISSUE THREAD

**Issue by ivanpu** [VSCodeEmacs/Emacs#4]
**Steps:**
1. Copy some text
2. Select another text
3. Press `Ctrl+Y`

**Expected result:**
The same as if in 3rd step I've selected `Paste` from the menu - selected text **is replaced** by the pasted text (but with addition of leaving mark mode, hence I don't want to just remap the keys)

**Actual results:**
It looks like first the selection is removed and only then the text **is appended** at the cursor location. The result is that the old text is still present and is not replaced.

**Additional information:**
I've seen the same behavior in other emacs-like extensions too, but I prefer this extension because the mark mode is not as frustrating as in the other ones.

**Comment by vdegenne** [comment]
Sorry I am not sure I can satisfy your request, in vanilla Emacs the selected text is not replaced, that is default behavior. Therefore it's better not implementing it.
There are two solutions, you could propose a PR to implement this behavior using a toggle property in the settings disabled by default. Or you could make an extension plugin that will cancel the native behavior over this one.

**Comment by ivanpu** [comment]
Ok, just checked on Emacs, and you are right.
Looks like I've for too long used other editors with Emacs keymap, and they do replace on paste...
Since this behavior is consistent with Emacs, I can live with it.
