### ISSUE TITLE
Is there any way to keep using meta(alt) in Mac?

### ISSUE THREAD

**Issue by kaiwk** [VSCodeEmacs/Emacs#5]
I used to use alt instead of cmd to keep consistency between different OS platform

**Comment by vdegenne** [comment]
There is no option to switch alt <=> cmd in this extension. If you want to hack your keys you should directly find a way directly into your system or you could also fork this extension and modify the `package.json` file and replace cmd with alt in the `mac` properties, it should work.

https://github.com/VSCodeEmacs/Emacs/pull/3/files
